### ISSUE TITLE
i have a 'allennlp.common.checks.ConfigurationError' help me!

### ISSUE THREAD

**Issue by jaeyun95** [Deanplayerljx/tab-vcr#2]
i enter 'python my_train.py -params models/r2c++_res101_attribute/default.json -folder models/saves/base -plot models/saves/base_plot' command.
i have a problem like this!

> Traceback (most recent call last):
>   File "my_train.py", line 104, in <module>
>     model = Model.from_params(vocab=train.vocab, params=params['model'])
>   File "/home/ailab/anaconda3/envs/tabvcr/lib/python3.6/site-packages/allennlp/common/from_params.py", line 263, in from_params
>     default_to_first_choice=default_to_first_choice)
>   File "/home/ailab/anaconda3/envs/tabvcr/lib/python3.6/site-packages/allennlp/common/params.py", line 259, in pop_choice
>     raise ConfigurationError(message)
> allennlp.common.checks.ConfigurationError: "MultiHopAttentionQABUA not in acceptable choices for model.type: ['bcn', 'constituency_parser', 'biaffine_parser', 'coref', 'crf_tagger', 'decomposable_attention', 'event2mind', 'simple_seq2seq', 'bidaf', 'bidaf-ensemble', 'dialog_qa', 'nlvr_coverage_parser', 'nlvr_direct_parser', 'quarel_parser', 'wikitables_mml_parser', 'wikitables_erm_parser', 'atis_parser', 'text2sql_parser', 'srl', 'simple_tagger', 'esim', 'bimpm', 'graph_parser', 'bidirectional-language-model', 'LSTMBatchNormBUAGlobalNoFinalImageFull']"
> 

help me~~~~~~!!!!!!:)
+ i find this choices list in allennlp library, but 'MultiHopAttentionQABUA' is not in this choices list.

> ['bcn', 'constituency_parser', 'biaffine_parser', 'coref', 'crf_tagger', 'decomposable_attention', 'event2mind', 'simple_seq2seq', 'bidaf', 'bidaf-ensemble', 'dialog_qa', 'nlvr_coverage_parser', 'nlvr_direct_parser', 'quarel_parser', 'wikitables_mml_parser', 'wikitables_erm_parser', 'atis_parser', 'text2sql_parser', 'srl', 'simple_tagger', 'esim', 'bimpm', 'graph_parser', 'bidirectional-language-model', 'LSTMBatchNormBUAGlobalNoFinalImageFull']

+ add!  --> i can train only 'base_res101_attribute'.  For training other code, Should i change other setting?

**Comment by Deanplayerljx** [comment]
Hi,

Please put your model name in the models/\_\_init\_\_.py file. I mentioned it in the Note section of the model folder's readme. :)

**Comment by jaeyun95** [comment]
oh! thank you~~~ :)
