### ISSUE TITLE
i have pytorch warning!

### ISSUE THREAD

**Issue by jaeyun95** [Deanplayerljx/tab-vcr#3]
code is run successfully! but this warning print in my terminal.
do you know how to solve this warning?
thank you~~:)

> /opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/ATen/native/cudnn/RNN.cpp:1236: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
> /opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
>

**Comment by Deanplayerljx** [comment]
Hi,

I also had these warnings, though I just ignored them... I think this will not affect the training.

**Comment by jaeyun95** [comment]
ok! thank you! :)

**Comment by AmingWu** [comment]
@jaeyun95, When I run the code, there is an error! python my_train.py -params r2c++_res101_attribute/default.json -folder saves/flagship_rationale -plot plt

OSError: Caught OSError in DataLoader worker process 0.

Could you give me some advice?

Thank you very much.
