### ISSUE TITLE
New Tag Feature Zip file

### ISSUE THREAD

**Issue by zyang-ur** [Deanplayerljx/tab-vcr#5]
Hi, thank you for your awesome work.

When I try to unzip the new tag features (https://drive.google.com/a/illinois.edu/file/d/1ajEVwLxJRCVhnhGKeBzvbeojSHczE4vJ/view?usp=sharing), the zip file shows "End-of-central-directory signature not found." As I've tried several times, I just wish to check if the zip works fine on your side?

Thank you so much.

**Comment by Deanplayerljx** [comment]
Hi,

Thanks for reporting this! It seems the zip files were broken... I have updated the links and it should work now.

Thanks!

**Comment by zyang-ur** [comment]
Thank you so much :)

**Comment by zyang-ur** [comment]
Please kindly update the link access at your convenience. Thank you.

**Comment by Deanplayerljx** [comment]
oops... I just updated the access setting. It should work now :)

**Comment by zyang-ur** [comment]
It works. Thank you so much.
