### ISSUE TITLE
the attributes and tag generation issues

### ISSUE THREAD

**Issue by runzeer** [Deanplayerljx/tab-vcr#6]
Great job!! But I have some questions about the attribute_feature and new_tag_feature generation. Could you share the codes about how to use the pretrained models in bottom-up-attention to generate the feature files?

**Comment by Deanplayerljx** [comment]
Hi,

I used the generate_tsv.py file in the [bottom-up-attention repo](https://github.com/peteanderson80/bottom-up-attention) repo to generate those features. For new tag feature, you can just change the input image to vcr images and run that code. For attribute_feature, you just need to use vcr's ground-truth bounding boxes as bounding box proposals and run the code.

**Comment by Pefect96** [comment]
> Great job!! But I have some questions about the attribute_feature and new_tag_feature generation. Could you share the codes about how to use the pretrained models in bottom-up-attention to generate the feature files?

I also need to extract the features and ask if you have generated them, thank you very much.
