### ISSUE TITLE
i want visualize attribute! 

### ISSUE THREAD

**Issue by jaeyun95** [Deanplayerljx/tab-vcr#8]
@Deanplayerljx 
i print attribute features use object_vocab.(provided h5 file index and object_vocab.txt)
it looks like label is same as new_tags label.
![image](https://user-images.githubusercontent.com/29617741/84780537-a6141f00-b020-11ea-9ead-a526a2f5f05e.png)
**this is original image**
![image](https://user-images.githubusercontent.com/29617741/84780585-b75d2b80-b020-11ea-97a4-92afef996cd0.png)
**this is attribute image( I received the data you provided)**
![image](https://user-images.githubusercontent.com/29617741/84780742-e6739d00-b020-11ea-82c9-637f920d4349.png)
**this is new_tags image( I received the data you provided)**

(1) new tag is used attribute feature??(not new_tags.h5, only attribute.h5)
(2) i want visualize 'attribute'! but i can't find index that is matching attribute vocab label .
where is attribute indices? help T^T

Thank you:)

**Comment by Deanplayerljx** [comment]
Hi, 

Sorry for the late reply. You can find the attribute information here.

For new tag boxes:
[train set](https://drive.google.com/file/d/1UI_T1IsWuozU42vGQrsRg6PzEtHCCNCz/view?usp=sharing)
[val set](https://drive.google.com/file/d/1eT-XB3dmFJbJ5M2HvUX-dSewAOFUgx_K/view?usp=sharing)

For original vcr boxes:
[train set](https://drive.google.com/file/d/13n2kvwhyvfLVzd4EGh_e-qLMzVHegobi/view?usp=sharing)
[val set](https://drive.google.com/file/d/1kB5ifWlw4XaClviVHbfVMGmPIgT-vZDK/view?usp=sharing)

Please use following script to read these files.
For new tag boxes (replace tsv with actual file name):

```
FIELDNAMES = ['image_id', 'num_boxes', 'boxes','objects', 'attrs']

imageid2det = {}
csv.field_size_limit(sys.maxsize)
with open(tsv, "r") as tsv_in_file:
    reader = csv.DictReader(tsv_in_file, delimiter='\t', fieldnames = FIELDNAMES)
    for item in reader:
        image_id = split + '-' + item['image_id']
        
        obj_indices = np.frombuffer(base64.b64decode(item['objects']),dtype=np.int)
        obj_names_dict = {}
        obj_names_list = []
        for obj_idx in obj_indices:
            
            obj_name = classes[obj_idx+1]
            obj_names_list.append(obj_name)
            if obj_name not in obj_names_dict:
                obj_names_dict[obj_name] = 0
            obj_names_dict[obj_name] += 1

        attr_indices = np.frombuffer(base64.b64decode(item['attrs']),dtype=np.int)
        num_boxes = int(item['num_boxes'])
        boxes = np.frombuffer(base64.b64decode(item['boxes']),dtype=np.float32).reshape(num_boxes, -1)
        imageid2det[image_id] = {'obj_names_dict':obj_names_dict, 'obj_names_list':obj_names_list,'objects': obj_indices, 'attrs':attr_indices, 'boxes':boxes}
```
For original vcr boxes (replace tsv_gt with actual file name):

```
FIELDNAMES_GT = ['image_id', 'num_boxes', 'boxes','objects', 'attrs']

imageid2det_gt = {}
csv.field_size_limit(sys.maxsize)
with open(tsv_gt, "r") as tsv_in_file:
    reader = csv.DictReader(tsv_in_file, delimiter='\t', fieldnames = FIELDNAMES_GT)
    for item in reader:
        image_id = split + '-' + item['image_id']

        obj_indices = item['objects']
        obj_indices = obj_indices.strip('[]')
        obj_indices = obj_indices.split(' ')
        obj_indices = filter(None,obj_indices)
        obj_indices = [int(x) for x in obj_indices]
        
        obj_names_dict = {}
        obj_names_list = []
        for obj_idx in obj_indices:
            obj_name = classes[obj_idx+1]
            obj_names_list.append(obj_name)
            if obj_name not in obj_names_dict:
                obj_names_dict[obj_name] = 0
            obj_names_dict[obj_name] += 1

        attr_indices = item['attrs']
        attr_indices = attr_indices.strip('[]')
        attr_indices = attr_indices.split(' ')
        attr_indices = filter(None,attr_indices)
        attr_indices = [int(x) for x in attr_indices]

        num_boxes = int(item['num_boxes'])
        boxes = np.frombuffer(base64.b64decode(item['boxes']),dtype=np.float32).reshape(num_boxes, -1)
        imageid2det_gt[image_id] = {'obj_names_dict':obj_names_dict, 'obj_names_list':obj_names_list,'objects': obj_indices, 'attrs':attr_indices, 'boxes':boxes}

```
